services:
  frontend:
    container_name: fluent-manager-frontend
    restart: always
    image: public.ecr.aws/apryse/fluent-manager-frontend:${FLUENT_MANAGER_VERSION}
    env_file: .env
    ports: ["80:8080"]
    depends_on: [backend]
    logging:
      driver: json-file
      options: { max-size: 50m, max-file: "3" }
  backend:
    container_name: fluent-manager-backend
    restart: always
    image: public.ecr.aws/apryse/fluent-manager-backend:${FLUENT_MANAGER_VERSION}
    env_file: .env
    depends_on: [db]
    logging:
      driver: json-file
      options: { max-size: 50m, max-file: "3" }
  db:
    container_name: fluent-manager-db
    restart: always
    image: public.ecr.aws/apryse/fluent-manager-db:${FLUENT_MANAGER_VERSION}
    volumes: ["fluent-manager-db:/var/lib/postgresql/data"]
    env_file: .env
    logging:
      driver: json-file
      options: { max-size: 50m, max-file: "3" }
  engine:
    container_name: fluent-engine
    restart: always
    image: public.ecr.aws/apryse/fluent-restful:${FLUENT_ENGINE_VERSION}
    ports:
      - 8080:8080
    env_file: .env
  fluent-sample-api:
    image: node:lts
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    ports:
      - 3000:3000
    command:
      npm --workspace @anthony-bonta-gaf-energy/fluent-sample-api run debug
volumes:
  fluent-manager-db: { name: fluent-manager-db }
networks:
  default: { name: fluent-manager-network }
